import assert from "node:assert/strict";
import fs from "node:fs";
import { BRICKLAYER_COLORS, COLOR_CODES, COLOR_NAMES, DEFAULT_PALETTE } from "../palette.js";
import { fallbackLayout } from "../pdf/pdf-utils.js";
import { generateConstructionLayout } from "../organizer.js";

const appSource = fs.readFileSync(new URL("../app.js", import.meta.url), "utf8");
const htmlSource = fs.readFileSync(new URL("../index.html", import.meta.url), "utf8");
const cssSource = fs.readFileSync(new URL("../styles.css", import.meta.url), "utf8");
const serviceWorkerSource = fs.readFileSync(new URL("../service-worker.js", import.meta.url), "utf8");

assert.equal(BRICKLAYER_COLORS.length, 15);
assert.deepEqual(COLOR_CODES, ["A", "N", "R", "B", "C", "M", "P", "G", "V", "L", "U", "S", "O", "I", "Q"]);
assert.equal(DEFAULT_PALETTE.A, "#F4C400");
assert.equal(DEFAULT_PALETTE.N, "#111111");
assert.equal(DEFAULT_PALETTE.R, "#D62828");
assert.equal(DEFAULT_PALETTE.B, "#F2F2F2");
assert.equal(DEFAULT_PALETTE.C, "#27C2D1");
assert.equal(DEFAULT_PALETTE.M, "#9B5A2E");
assert.equal(DEFAULT_PALETTE.P, "#D9A074");
assert.equal(DEFAULT_PALETTE.G, "#808080");
assert.equal(DEFAULT_PALETTE.V, "#009B55");
assert.equal(DEFAULT_PALETTE.L, "#7B3FB2");
assert.equal(COLOR_NAMES.U, "Azul");
assert.equal(COLOR_NAMES.S, "Rosado");
assert.equal(COLOR_NAMES.O, "Naranja");
assert.equal(COLOR_NAMES.I, "Lila");
assert.equal(COLOR_NAMES.Q, "Marron claro");

assert.ok(appSource.includes("function selectColor(code)"));
assert.ok(appSource.includes('state.tool = "paint"'));
assert.ok(appSource.includes("function shouldIgnoreShortcut(event)"));
assert.ok(appSource.includes('tag === "INPUT"'));
assert.ok(appSource.includes('tag === "TEXTAREA"'));
assert.ok(appSource.includes('tag === "SELECT"'));
assert.ok(appSource.includes('key === "e"'));
assert.ok(appSource.includes('setTool("erase")'));
assert.ok(appSource.includes('key === "f"'));
assert.ok(appSource.includes('setTool("reference")'));
assert.ok(appSource.includes('key === "t"'));
assert.ok(appSource.includes('setTool("template")'));
assert.ok(appSource.includes('key === "k"'));
assert.ok(appSource.includes("addLayer()"));
assert.ok(appSource.includes('key === "d"'));
assert.ok(appSource.includes("duplicateCurrentLayer()"));
assert.ok(appSource.includes('key === "z"'));
assert.ok(appSource.includes("undo()"));
assert.ok(appSource.includes('key === "y"'));
assert.ok(appSource.includes("redo()"));
assert.ok(appSource.includes('event.key === "ArrowLeft"'));
assert.ok(appSource.includes('event.key === "ArrowRight"'));
assert.ok(appSource.includes("firstLayer()"));
assert.ok(appSource.includes("lastLayer()"));
assert.ok(appSource.includes("if (event.ctrlKey || event.altKey || event.metaKey) return;"));
assert.ok(!appSource.includes("if (event.ctrlKey && !event.altKey && !event.metaKey)"));
assert.ok(appSource.includes("toggleEditorLock()"));
assert.ok(appSource.includes("zoomIn()"));
assert.ok(appSource.includes("zoomOut()"));
assert.ok(appSource.includes("fitZoom()"));
assert.ok(appSource.includes("calculateFitCellSize()"));
assert.ok(appSource.includes("centerGridInViewport()"));
assert.ok(appSource.includes("ResizeObserver"));
assert.ok(appSource.includes('state.zoomMode = "fit"'));
assert.ok(appSource.includes("getBoundingClientRect()"));
assert.ok(appSource.includes('APPEARANCE_STORAGE_KEY = "bricklayer-mobile-appearance-v1"'));
assert.ok(appSource.includes("setInterfaceBackground"));
assert.ok(appSource.includes("resetInterfaceBackground"));
assert.ok(appSource.includes("themeFromBackground"));
assert.ok(appSource.includes("createReferenceAt(col, row)"));
assert.ok(appSource.includes("nextReferenceId()"));
assert.ok(appSource.includes('import { REFERENCE_TYPES, isReferenceVisibleAtZ'));
assert.ok(appSource.includes('import { MAX_LDR_BYTES, UnsupportedLDrawPiecesError, importLdrContent, projectNameFromLdrFilename } from "./ldr-importer.js"'));
assert.ok(appSource.includes("importLdrProject"));
assert.ok(appSource.includes("activeReferencesForCurrentLayer()"));
assert.ok(appSource.includes("isReferenceVisibleAtZ(reference, z)"));
assert.ok(appSource.includes("pointer-events: none") || cssSource.includes("pointer-events: none"));
assert.ok(appSource.includes("beginImageDrag"));
assert.ok(appSource.includes("setImageScale"));
assert.ok(appSource.includes("openContextPanel"));
assert.ok(appSource.includes("closeContextPanel"));
assert.ok(appSource.includes("contrastText"));
assert.ok(appSource.includes("openShortcutsBtn"));

assert.ok(htmlSource.includes('class="tool-rail"'));
assert.ok(htmlSource.includes('id="contextPanel"'));
assert.ok(htmlSource.includes('data-panel-target="layers"'));
assert.ok(htmlSource.includes('data-panel-target="blocks"'));
assert.ok(htmlSource.includes('data-panel-target="references"'));
assert.ok(htmlSource.includes('data-panel-target="image"'));
assert.ok(htmlSource.includes('data-panel-target="view3d"'));
assert.ok(htmlSource.includes('data-panel-target="project"'));
assert.ok(htmlSource.includes('data-panel-target="settings"'));
assert.ok(htmlSource.includes("Importar LDR"));
assert.ok(htmlSource.includes('id="ldrImportInput" type="file"'));
assert.ok(htmlSource.includes('accept=".ldr,.ldr.txt,text/plain"'));
assert.ok(htmlSource.includes("Fondo de interfaz"));
assert.ok(htmlSource.includes("Fondo visor 3D"));
assert.ok(htmlSource.includes('data-app-background="default"'));
assert.ok(htmlSource.includes('data-app-background="black"'));
assert.ok(htmlSource.includes('data-app-background="gray"'));
assert.ok(htmlSource.includes('data-app-background="light"'));
assert.ok(htmlSource.includes('id="customBackgroundColor" type="color"'));
assert.ok(htmlSource.includes('id="resetBackgroundBtn"'));
assert.ok(htmlSource.includes('data-viewer-background="dark"'));
assert.ok(htmlSource.includes('id="customViewerBackgroundColor" type="color"'));
assert.ok(htmlSource.includes('id="resetViewerBackgroundBtn"'));
assert.ok(htmlSource.includes('data-panel-target="help"'));
assert.ok(htmlSource.includes('id="editorModeBtn"'));
assert.ok(htmlSource.includes('id="dragPaintToggle"'));
assert.ok(htmlSource.includes('id="referenceMode"'));
assert.ok(htmlSource.includes('data-reference-mode="NORMAL"'));
assert.ok(htmlSource.includes('data-reference-mode="TEMPORAL_NEXT_LAYER"'));
assert.ok(htmlSource.includes('data-reference-mode="BACKWARD"'));
assert.ok(htmlSource.includes('id="imageEditBtn"'));
assert.ok(htmlSource.includes('id="blockOpacity"'));
assert.ok(htmlSource.indexOf('class="tool-rail"') < htmlSource.indexOf('id="matrixGrid"'));
assert.ok(htmlSource.indexOf('id="matrixGrid"') < htmlSource.indexOf('class="palette-rail"'));
assert.ok(htmlSource.includes('data-tool="template"'));
assert.ok(htmlSource.includes('type="module" src="./app.js?v=viewer3d-recolor-v3"'));
assert.ok(htmlSource.includes('id="shortcutsDialog"'));
assert.ok(htmlSource.includes('id="openShortcutsBtn"'));
assert.ok(htmlSource.includes('id="gridZoom" type="range" min="8"'));
assert.ok(htmlSource.includes('data-panel-target="colors"'));
assert.ok(htmlSource.includes('id="currentColorSwatch"'));
assert.ok(htmlSource.includes("<kbd>K</kbd> Nueva capa"));
assert.ok(htmlSource.includes("<kbd>D</kbd> Duplicar capa"));
assert.ok(htmlSource.includes("<kbd>Z</kbd> Deshacer"));
assert.ok(htmlSource.includes("<kbd>Y</kbd> Rehacer"));
assert.ok(!htmlSource.includes("<kbd>Ctrl</kbd>"));
assert.ok(cssSource.includes("grid-template-columns: 70px minmax(0, 1fr) 58px;"));
assert.ok(cssSource.includes("grid-template-rows: auto minmax(0, 1fr);"));
assert.ok(cssSource.includes("height: 100dvh;"));
assert.ok(cssSource.includes("overflow: hidden;"));
assert.ok(cssSource.includes(".context-panel {\n  position: absolute;"));
assert.ok(cssSource.includes("left: 78px;"));
assert.ok(cssSource.includes("overflow-y: auto;"));
assert.ok(cssSource.includes(".editor-center {\n  grid-column: 1;"));
assert.ok(cssSource.includes("grid-template-rows: minmax(0, 1fr) auto;"));
assert.ok(cssSource.includes("grid-row: 2;"));
assert.ok(!cssSource.includes("position: fixed;\n    left: 6px;"));
assert.ok(cssSource.includes("min-height: var(--cell);"));
assert.ok(cssSource.includes("--app-bg"));
assert.ok(cssSource.includes("--viewer3d-bg"));
assert.ok(cssSource.includes(".viewer3d-recolor-bar"));
assert.ok(cssSource.includes(".appearance-section"));
assert.ok(cssSource.includes(".palette-rail.mobile-open"));
assert.ok(cssSource.includes("bottom: 58px;"));
assert.ok(serviceWorkerSource.includes("./reference-utils.js"));
assert.ok(serviceWorkerSource.includes("./ldr-importer.js"));
assert.ok(serviceWorkerSource.includes('CACHE_NAME = "bricklayer-mobile-v21"'));
assert.ok(serviceWorkerSource.includes("isNetworkFirstAsset"));
assert.ok(serviceWorkerSource.includes("./selection3d.js"));
assert.ok(serviceWorkerSource.includes("./viewer3d-model.js"));
assert.ok(serviceWorkerSource.includes("./brickai-package.js"));
assert.ok(serviceWorkerSource.includes("./brickai-renderer.js"));
assert.ok(serviceWorkerSource.includes("./brickai-zip.js"));

const project = {
  format: "bricklayers-v1",
  name: "Paleta 15",
  size: { x: 5, y: 1 },
  palette: DEFAULT_PALETTE,
  revision: 1,
  references: [{ id: "R1", x: 0, y: 0, start_z: 0, end_z: null, label: "" }],
  layers: [{ z: 0, matrix: ["USOIQ"] }]
};
const fallback = fallbackLayout(project);
assert.deepEqual(Object.keys(fallback.inventory).sort(), ["I", "O", "Q", "S", "U"]);
const layout = generateConstructionLayout(project, { maxPieceLength: 3, priority: "balanced" });
assert.equal(layout.totals.cells, 5);
assert.ok(!layout.pieces.some((piece) => piece.id === "R1"));

console.log("editor UX tests OK");
